version: '3.8'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432  # make sure you don't have another container running on 5432
    environment:
      - POSTGRES_DB=shop
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    version: '3.8'
    # If using Neon, your database connection details will be in the .env file
    # and should be prefixed with PG_ and comment the code from db section else 
    # use this as it is
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production

  # Additional tools can be added here
#conn string - postgres://asad:asad123@localhost:5432/online-shop
